# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param a the fixed parameter greater than 0
#' @param b the fixed parameter greater than 0
#' @param n the integer parameter
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(2000,1,4,50,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, a, b, n, thin) {
    .Call('_StatComp21017_gibbsC', PACKAGE = 'StatComp21017', N, a, b, n, thin)
}

